version: '3.5'

services:
  vault:
    image: vault:1.6.2
    container_name: vault
    restart: always
    entrypoint: /bin/vault
    command:
      - server
      - -config=/vault/config/vault-config.hcl
    environment: {}
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-log-vol:/vault/logs
      - vault-file-vol:/vault/file
      - ./vault-config.hcl:/vault/config/vault-config.hcl
    networks:
      - vault
    ports:
      - 8200:8200
    expose:
      - "8200"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./site_config.conf:/etc/nginx/conf.d/default.conf
      # - <path/to/your/certs>:/etc/ssl/private
    networks:
      - vault

volumes:
  vault-log-vol:
  vault-file-vol:

networks:
  vault:
    name: vault